name: "CD #2 - El Almacen de Ejecutables"

# Se activa manualmente o en push a main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  empaquetar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generar paquete WAR (sin tests)
        run: mvn -B clean package -DskipTests

      - name: Subir WAR como artefacto descargable
        uses: actions/upload-artifact@v4
        with:
          name: AuraReviews-WAR
          path: target/*.war
