name: "CD #1 - Despliegue Manual"

# Solo se ejecuta manualmente desde la interfaz de GitHub (boton "Run workflow")
on:
  workflow_dispatch:
  push:
    branches:
      - fix9

jobs:
  empaquetar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Generar paquete WAR
        run: mvn -B clean package -DskipTests
