name: "CD #3 - Publicacion de Versiones Oficiales (Releases)"

# Se activa cuando se crea un tag que empiece por "v" (ej: v1.0.0, v2.1.3)
on:
  push:
    branches:
      - fix2-ci-workflows
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Generar paquete WAR
        run: mvn -B clean package -DskipTests

      - name: Crear Release en GitHub y adjuntar WAR
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.war
          generate_release_notes: true
