name: "CI #1 - El Vigilante Universal"

# Se activa en cada push a CUALQUIER rama del repositorio
on:
  push:

jobs:
  compilar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar con Maven
        run: mvn compile
